# Generated by Django 5.0.4 on 2024-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('riderid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(choices=[('District 1', 'District 1'), ('District 2', 'District 2')], max_length=75)),
                ('availability', models.BooleanField(blank=True, default=False, max_length=15, null=True)),
                ('contactnum', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
