# Generated by Django 5.0.4 on 2024-04-11 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('dispatchid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Preparing', 'Preparing'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='Preparing', max_length=20)),
                ('order', models.CharField(max_length=20)),
                ('orderpayment', models.CharField(choices=[('Card', 'Card'), ('GCASH', 'GCASH'), ('COD', 'COD')], max_length=20)),
                ('dropoff', models.CharField(max_length=500)),
                ('pickup', models.CharField(max_length=500)),
                ('deliverydate', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
                ('dispatchrider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rider.rider')),
            ],
        ),
    ]
